### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by ghost** [ServiceStackApps/Northwind#1]
I was using your Northwind API in one of my AngularJS classes for a simple $http service demonstration but your API was not working because no Cross-Origin Resource Sharing (CORS) was enabled from the back-end or your side so I want you to enable it from the back-end so the API and services you hosted will be more usable in that case.

While I am not a C# or APS.NET expert but I think something like this: `Response.AddHeader("Access-Control-Allow-Origin", "*");` will solve the problem but I am not pretty sure.

Thanks in advance

**Comment by mythz** [comment]
There's a bit more to it than that, but in ServiceStack it's just:

``` csharp
Plugins.Add(new CorsFeature());
```

Which I've now added in this commit: https://github.com/ServiceStackApps/Northwind/commit/6d528ae156c50713febd10d3739f6599c37f7e4a

And just deployed to: http://northwind.servicestack.net so you should now be able to access it.
